// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function ListData(tablename: string): $CancellablePromise<{ [_: string]: string }[]> {
    return $Call.ByID(1448516340, tablename).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListStructure(tablename: string): $CancellablePromise<{ [_: string]: string }[]> {
    return $Call.ByID(1818912865, tablename).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListTable(): $CancellablePromise<string[]> {
    return $Call.ByID(3296071872).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
