// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-sm mx-auto\"><h1 class=\"my-8 text-2xl font-semibold dark:text-white\">Connect with Sherlock</h1><div class=\"flex mb-2\"><div><label class=\"block dark:text-white\">Host</label> <input class=\"bg-gray-100/25 dark:text-white block w-full px-2 py-1 rounded-lg\" id=\"host\" placeholder=\"localhost\"></div><div class=\"ml-2\"><label class=\"block dark:text-white\">Port</label> <input class=\"bg-gray-100/25 dark:text-white block w-full px-2 py-1 rounded-lg\" id=\"port\" placeholder=\"5432\"></div></div><div class=\"mb-2 flex flex-col\"><label class=\"block dark:text-white\">User</label> <input class=\"bg-gray-100/25 dark:text-white block w-full px-2 py-1 rounded-lg\" id=\"user\"></div><div class=\"mb-2 flex flex-col\"><label class=\"block dark:text-white\">Password</label> <input class=\"bg-gray-100/25 dark:text-white block w-full px-2 py-1 rounded-lg\" type=\"password\" id=\"password\"></div><div class=\"mb-4 flex flex-col\" id=\"db-input-div\"><label class=\"block dark:text-white\">Database</label> <input class=\"bg-gray-100/25 dark:text-white block w-full px-2 py-1 rounded-lg\" id=\"database\"></div><div class=\"text-red-500 hidden mb-4\" id=\"pg-connect-error\">Connection refused</div><div class=\"flex justify-end\"><button onclick=\"Connect()\" class=\"rounded-lg px-2 py-1 bg-blue-500 dark:text-white\">Connect</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
